### PR TITLE
Added funcional RegisterForm and class working with users.xml

### PR DESCRIPTION
**Pull request by Mattynas**

### CODE REVIEW

**Comment by JaCobbMedia** [comment]
users.xml add to .gitignore

**Review by max-prokofjev — APPROVED** [review]
all good, agree with Jokubas

**Comment by Mattynas** [comment]
how to do that?

**Comment by max-prokofjev** [comment]
just write path to git ignore file in main directory, login/users.xml i think

**Review by ghost — APPROVED** [review]

**Pull request closed without merging**
